---
title: "Solution Bram"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
d_irene <- read.table("Irenes_data.txt", header=T)
```

# function to resample the dataframe
```{r}

resample <- function(){
  d_resampled <- d_irene[0,] # create empty dataframe
  for (tree in unique(d_irene$tree_id)){ # for every unique tree
    sub_d1 <- subset(d_irene, tree_id==tree) # subset the data
    d2 <- sub_d1[sample(nrow(sub_d1)),] # resample the subsetted data
    d2 <- d2[1:(48/d2$specrich[1]),] # take the first 16, 24 or 48 rows depending on the species richness
    d_resampled <- rbind(d_resampled,d2) # bind selected rows to dataframe
  return(d_resampled)
  }
}
```

# run models and extract AIC 1000 times
```{r}
  model_outputs <- data.frame(model = character(0), aic = numeric(0), stringsAsFactors = F)
  for (i in 1:1000){
    d_resampled <- resample()
    m1 <- glm(abun ~ fragmean + total_all_ba, data=d_resampled)
    m2 <- glm(abun ~ -1 + rel_qrob + rel_qrub + rel_fsyl + fragmean + total_all_ba, data=d_resampled)
    m3 <- glm(abun ~ -1 + rel_qrob + rel_qrub + rel_fsyl + fragmean + total_all_ba + rel_qrob:rel_qrub +  rel_qrob:rel_fsyl + rel_qrub:rel_fsyl, data=d_resampled)
    
    model_outputs[(i-1)*3+1,1] <- "m1"
    model_outputs[(i-1)*3+1,2] <- m1$aic
    model_outputs[(i-1)*3+2,1] <- "m2"
    model_outputs[(i-1)*3+2,2] <- m2$aic
    model_outputs[(i-1)*3+3,1] <- "m3"
    model_outputs[(i-1)*3+3,2] <- m3$aic
  }

```


# intermediate without function

```{r}
start_time <- Sys.time()
model_outputs <- data.frame(model = character(0), aic = numeric(0), stringsAsFactors = F)
for (i in 1:10){
  d_resampled <- d_irene[0,] # create empty dataframe
  for (tree in unique(d_irene$tree_id)){ # for every unique tree
    sub_d1 <- subset(d_irene, tree_id==tree) # subset the data
    d2 <- sub_d1[sample(nrow(sub_d1)),] # resample the subsetted data
    d2 <- d2[1:(48/d2$specrich[1]),] # take the first 16, 24 or 48 rows depending on the species richness
    d_resampled <- rbind(d_resampled,d2) # bind selected rows to dataframe
  }
  
  m1 <- glm(abun ~ fragmean + total_all_ba, data=d_resampled)
  m2 <- glm(abun ~ -1 + rel_qrob + rel_qrub + rel_fsyl + fragmean + total_all_ba, data=d_resampled)
  m3 <- glm(abun ~ -1 + rel_qrob + rel_qrub + rel_fsyl + fragmean + total_all_ba + rel_qrob:rel_qrub +  rel_qrob:rel_fsyl + rel_qrub:rel_fsyl, data=d_resampled)
  
  model_outputs[(i-1)*3+1,1] <- "m1"
  model_outputs[(i-1)*3+1,2] <- m1$aic
  model_outputs[(i-1)*3+2,1] <- "m2"
  model_outputs[(i-1)*3+2,2] <- m2$aic
  model_outputs[(i-1)*3+3,1] <- "m3"
  model_outputs[(i-1)*3+3,2] <- m3$aic
}
end_time <- Sys.time()
end_time - start_time
```


#evaluating the best model
```{r}
ggplot(model_outputs, aes(x= model, y=aic))+
  geom_boxplot()

best_model <- model_outputs %>% group_by(model) %>% summarize(mean_aic=mean(aic), sd_aic = sd(aic))
best_model
       
```


